### ISSUE TITLE
 bmi Request has already been read

### ISSUE THREAD

**Issue by Jimmey-Jiang** [apache/servicecomb-samples#105]
![image](https://user-images.githubusercontent.com/28785691/210747921-ee0431af-4b8b-40a4-86c9-79cad91523b3.png)

**Comment by Jimmey-Jiang** [comment]
https://servicecomb.apache.org/cn/docs/products/java-chassis/quick-start/

**Comment by liubao68** [comment]
Maybe you need change https://github.com/apache/servicecomb-samples/blob/master/java-chassis-samples/bmi/webapp/src/main/resources/application.yml  `gateway.webroot` property.

**Comment by Jimmey-Jiang** [comment]
11
