### ISSUE TITLE
mvn clean install errors in  metrics-extend-healthcheck

### ISSUE THREAD

**Issue by surechen** [apache/servicecomb-samples#38]
1.
I execute commd 'mvn clean install' in ./java-chassis-samples. And then get errors.

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.apache.servicecomb:java-chassis-spring-boot-starter-servlet:jar is missing. @ line 38, column 17
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.apache.servicecomb.samples:metrics-extend-healthcheck:2.0.0-SNAPSHOT (/opt/testjava/servicecomb-samples/java-chassis-samples/metrics-extend-healthcheck/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.apache.servicecomb:java-chassis-spring-boot-starter-servlet:jar is missing. @ line 38, column 17
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

When I add  <dependency>
      <groupId>org.apache.servicecomb</groupId>
      <artifactId>java-chassis-spring-boot-starter-servlet</artifactId>
      <version>2.0.0-SNAPSHOT</version>
    </dependency>
I get anothor err:
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.apache.servicecomb:java-chassis-spring-boot-starter-servlet:jar:2.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Java Chassis::Samples 2.0.0-SNAPSHOT:
[INFO]
[INFO] Java Chassis::Samples .............................. SUCCESS [  0.246 s]
[INFO] Java Chassis::Samples::Common Schema ............... SUCCESS [  1.246 s]
[INFO] Java Chassis::Samples::CodeFirst ................... SUCCESS [  0.005 s]
[INFO] Java Chassis::Samples::CodeFirst::Provider ......... SUCCESS [01:42 min]
[INFO] Java Chassis::Samples::CodeFirst::Consumer ......... SUCCESS [  0.096 s]
[INFO] Java Chassis::Samples::Custom Handler .............. SUCCESS [  0.004 s]
[INFO] Java Chassis::Samples::Custom Handler::Consumer .... SUCCESS [  7.731 s]
[INFO] Java Chassis::Samples::Custom Handler::Provider .... SUCCESS [  0.076 s]
[INFO] Java Chassis::Samples::JAXRS ....................... SUCCESS [  0.003 s]
[INFO] Java Chassis::Samples::JAXRS::Provider ............. SUCCESS [ 13.595 s]
[INFO] Java Chassis::Samples::JAXRS::Consumer ............. SUCCESS [  0.104 s]
[INFO] pojo-sample ........................................ SUCCESS [  0.004 s]
[INFO] pojo-provider ...................................... SUCCESS [  0.107 s]
[INFO] pojo-consumer ...................................... SUCCESS [  0.071 s]
[INFO] springmvc-sample ................................... SUCCESS [  0.004 s]
[INFO] springmvc-provider ................................. SUCCESS [  0.083 s]
[INFO] springmvc-consumer ................................. SUCCESS [  0.111 s]
[INFO] Java Chassis::Samples::Auth ........................ SUCCESS [  0.004 s]
[INFO] auth-provider ...................................... SUCCESS [  0.088 s]
[INFO] Java Chassis::Samples::Auth::Consumer .............. SUCCESS [  0.067 s]
[INFO] Java Chassis::Samples::Metrics ..................... SUCCESS [  0.003 s]
[INFO] Java Chassis::Samples::Metrics::Write File ......... SUCCESS [  0.137 s]
[INFO] Java Chassis::Samples::Metrics::Health Check ....... FAILURE [  0.071 s]
[INFO] config-apollo-sample ............................... SKIPPED
[INFO] use-log4j2-sample .................................. SKIPPED
[INFO] Java Chassis::Demo::Local service registry ......... SKIPPED
[INFO] Java Chassis::Demo::LocalRegistry::Server .......... SKIPPED
[INFO] Java Chassis::Demo::LocalServiceRegistry::Client ... SKIPPED
[INFO] trust-sample ....................................... SKIPPED
[INFO] store .............................................. SKIPPED
[INFO] customer ........................................... SKIPPED
[INFO] hacker ............................................. SKIPPED
[INFO] Java Chassis::Samples::apm-agent ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:06 min
[INFO] Finished at: 2019-12-18T16:25:01+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project metrics-extend-healthcheck: Could not resolve dependencies for project org.apache.servicecomb.samples:metrics-extend-healthcheck:jar:2.0.0-SNAPSHOT: Could not find artifact org.apache.servicecomb:java-chassis-spring-boot-starter-servlet:jar:2.0.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :metrics-extend-healthcheck

![image](https://user-images.githubusercontent.com/7249331/71069419-a8053e80-21b3-11ea-840a-5a2c42966842.png)

**Comment by liubao68** [comment]
Do you compile latest java-chassis locally? This samples use the latest code. And you can check out branch 1.3.0 samples if you are not using the latest.
