### ISSUE TITLE
can not create a new instance with new port 

### ISSUE THREAD

**Issue by huaian** [apache/servicecomb-samples#54]
steps:
#cd /opt/develop/servicecomb-samples/java-chassis-samples/bmi/calculator
# mvn spring-boot:run -Drun.jvmArguments="-Dcse.rest.address=0.0.0.0:7778"

[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.2.RELEASE:run (default-cli) on project bmi-calculator: An exception occurred while running. null: InvocationTargetException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat: **java.net.BindException: Address already in use (Bind failed) -> [Help 1]**

refer to link: https://servicecomb.apache.org/cn/docs/products/java-chassis/load-balance/

**Comment by huaian** [comment]
server.port 也要修改成7778才行

**Comment by liubao68** [comment]
https://docs.servicecomb.io/java-chassis/zh_CN/featured-topics/application-bmi/load-balance/

This is the latest document. The official site using a different demo repository and there are some bit different. I am going to create an issue to remove the docs.

**Comment by huaian** [comment]
thanks, guide is important. please make this update asap!
