### ISSUE TITLE
在CSE中使用Handler进行拦截时，抛出的异常如何正常回显至调用方

### ISSUE THREAD

**Issue by 992923410** [apache/servicecomb-samples#59]
在CSE中使用Handler进行拦截时，Handler抛出了相应的自定义异常，CSE会对异常进行封装，如何让CSE不进行原异常的封装而是原异常抛出
![微信图片_20201106103642](https://user-images.githubusercontent.com/54975068/98319575-fca7e700-201b-11eb-9bcb-695205282568.png)

**Comment by liubao68** [comment]
不可以直接返回原始异常的。一方面是考虑exception的序列化问题，java-chassis是类型无关（跨语言）的RPC，不能包含类型信息；另一方面不反悔原始异常也是考虑信息泄露问题。 可以考虑[异常处理](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/error-handling/)来返回更加友好的经过处理的信息。

**Comment by 992923410** [comment]
感谢回答！
还有个问题，在handler中使用@Autowired进行注入发现均为null值，是需要配置其他东西吗？
![微信图片_20201109111437](https://user-images.githubusercontent.com/54975068/98496635-0e3bf980-227d-11eb-88bd-183a89076a81.png)

**Comment by liubao68** [comment]
Handler 不是 spring bean， 因此无法注入 spring bean。 需要采用一些技巧实现在非 spring bean 中使用 bean。 比如通过 BeanUtils 或者 增加一个 bean, 提供 static 方法获取。
