### ISSUE TITLE
指标服务的端口是多少？在哪查看？

### ISSUE THREAD

**Issue by sofkyle** [apache/servicecomb-samples#90]
已经设置了rest接口为8081，发现无法查看metrics数据：
配置：
![image](https://user-images.githubusercontent.com/7426860/157154373-c508a2c6-4307-49fe-b388-1ddabd3cec07.png)

调用：
![image](https://user-images.githubusercontent.com/7426860/157154396-932764f3-174d-46fc-a50a-c5acab2c6b23.png)

**Comment by liubao68** [comment]
和应用一样的端口。 看下 [开发指南](https://servicecomb.apache.org/references/java-chassis/zh_CN/general-development/metrics.html) 是否缺失了相关包？

**Comment by sofkyle** [comment]
谢谢，问题已经解决，IDEA上没刷新maven引用

**Comment by sofkyle** [comment]
谢谢，问题已经解决，IDEA上没刷新maven引用
